//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpEval.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharpEval.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn command echo on or off.
        /// </summary>
        internal static string CmdEcho {
            get {
                return ResourceManager.GetString("CmdEcho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit program.
        /// </summary>
        internal static string CmdExit {
            get {
                return ResourceManager.GetString("CmdExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load a .cs file into the execution engine. Parameter must be an existing C# file with .cs extension.
        /// </summary>
        internal static string CmdLoad {
            get {
                return ResourceManager.GetString("CmdLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change angle mode. Supported modes: deg, rad, grad.
        /// </summary>
        internal static string CmdMode {
            get {
                return ResourceManager.GetString("CmdMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset evaluator &amp; clean variables.
        /// </summary>
        internal static string CmdReset {
            get {
                return ResourceManager.GetString("CmdReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn stack trace display on or off, when an error occures.
        /// </summary>
        internal static string CmdTrace {
            get {
                return ResourceManager.GetString("CmdTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display variables.
        /// </summary>
        internal static string CmdVars {
            get {
                return ResourceManager.GetString("CmdVars", resourceCulture);
            }
        }
    }
}
